name: downstairs
description: A Game going Downstairs
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  audioplayers: ^3.0.0
  bloc: ^8.1.1
  equatable: ^2.0.5
  flame: ^1.6.0
  flame_audio: ^1.4.0
  flame_behaviors: ^0.2.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.1
  intl: ^0.17.0
  mockingjay: ^0.3.0

dev_dependencies:
  bloc_test: ^9.1.1
  flame_test: ^1.8.0
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter_launcher_icons:
  image_path: "assets/images/downstairs_logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "#f5edcc" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/downstairs_logo.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/images/downstairs_logo.png"
  windows:
    generate: true
    image_path: "assets/images/downstairs_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/downstairs_logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/
